"""table

Revision ID: 6a3652dea4d4
Revises: 5e4cdf1161e3
Create Date: 2025-07-28 11:29:29.138634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3652dea4d4'
down_revision = '5e4cdf1161e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_bookings_table_id', 'tables', ['table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###
