"""Add role to employee

Revision ID: 853e7eeca3eb
Revises: 49c8c841a9f6
Create Date: 2025-07-29 10:16:22.702470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853e7eeca3eb'
down_revision = '49c8c841a9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
